spring:
  application:
    name: payment-service
  temporal:
    namespace: default
    connection:
      target: 127.0.0.1:7233
    workersAutoDiscovery:
      packages: com.github.cobrijani.paymentservice
server:
  port: 8083